version: '3.8'
services: 
    autocomplete-service:
        build: ./src/
        volumes: 
            - ./src/:/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            FLASK_ENV: development