version: '3.8'
services: 
    autocomplete-restapi:
        build: ./autocomplete-restapi/
        volumes: 
            - ./autocomplete-restapi/:/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            FLASK_ENV: development